In [1]:
import pandas as pd
import seaborn as sns
from pandas_datareader import data
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import csv

In [2]:
esg={}
with open('C:/Users/kay31/Desktop/final/ESG表.csv',newline='', encoding="BIG5", errors='ignore') as csvfile:
  esg = csv.DictReader(csvfile)
  esg_df = pd.DataFrame(esg)
for column in esg_df:
  esg_df[column] = pd.to_numeric(esg_df[column],errors='coerce')
esg_df

short_name  stk_no  zh_name  sector  esg_score    年化夏普比率     年化波動度  \
0           NaN    1101      NaN     NaN      21.41 -0.988816  0.150810   
1           NaN    1102      NaN     NaN      27.48  0.392474  0.128489   
2           NaN    1103      NaN     NaN      38.46 -0.712963  0.134292   
3           NaN    1104      NaN     NaN      31.33  0.666322  0.105792   
4           NaN    1201      NaN     NaN      36.43 -0.915084  0.109402   
5           NaN    1210      NaN     NaN      37.17 -0.469965  0.133379   
6           NaN    1215      NaN     NaN      37.67  0.840844  0.104729   
7           NaN    1216      NaN     NaN      28.53  0.367578  0.111166   
8           NaN    1218      NaN     NaN      26.90  1.725006  0.278537   
9           NaN    1227      NaN     NaN      27.89 -1.138330  0.125473   
10          NaN    1229      NaN     NaN      27.89 -0.181497  0.183784   
11          NaN    1231      NaN     NaN      41.26  0.812680  0.217245   
12          NaN    1232      NaN     NaN      29.70  0.039698  0.116154   
13          NaN    1301      NaN     NaN      22.51 -0.261934  0.148727   
14          NaN    1303      NaN     NaN      26.11  0.136776  0.160818   
15          NaN    1304      NaN     NaN      23.81 -0.759182  0.259122   
16          NaN    1305      NaN     NaN      29.34 -1.123382  0.230671   
17          NaN    1308      NaN     NaN      24.42 -0.371319  0.284339   
18          NaN    1312      NaN     NaN      26.81 -0.869822  0.204642   
19          NaN    1313      NaN     NaN      25.83 -1.134268  0.255056   
20          NaN    1314      NaN     NaN      24.62 -0.565696  0.226073   
21          NaN    1319      NaN     NaN      30.32  1.123647  0.279990   
22          NaN    1326      NaN     NaN      24.27  0.207750  0.134427   
23          NaN    1402      NaN     NaN      22.77  1.165732  0.138536   
24          NaN    1409      NaN     NaN      29.71 -0.075378  0.144751   
25          NaN    1434      NaN     NaN      15.49 -0.319148  0.102485   
26          NaN    1440      NaN     NaN      21.56 -0.703081  0.242670   
27          NaN    1476      NaN     NaN      15.67 -0.561605  0.300941   
28          NaN    1477      NaN     NaN      15.59  0.136045  0.299679   
29          NaN    1504      NaN     NaN      21.66 -0.211857  0.171222   
..          ...     ...      ...     ...        ...       ...       ...   
353         NaN    8016      NaN     NaN      39.12 -0.447292  0.320401   
354         NaN    8044      NaN     NaN      28.46 -2.134284  0.372412   
355         NaN    8046      NaN     NaN      22.25 -1.529975  0.424104   
356         NaN    8069      NaN     NaN      19.16  0.700880  0.439447   
357         NaN    8070      NaN     NaN      12.96 -0.024237  0.239347   
358         NaN    8081      NaN     NaN      43.24 -1.245969  0.315540   
359         NaN    8086      NaN     NaN      22.17 -1.345743  0.374455   
360         NaN    8112      NaN     NaN      12.80 -0.248330  0.198299   
361         NaN    8131      NaN     NaN      31.11  0.590013  0.132069   
362         NaN    8150      NaN     NaN      22.63 -0.744987  0.233444   
363         NaN    8163      NaN     NaN      17.57 -0.254775  0.207886   
364         NaN    8299      NaN     NaN      21.67 -0.429319  0.312057   
365         NaN    8341      NaN     NaN      22.63 -1.369233  0.189985   
366         NaN    8358      NaN     NaN      21.89 -0.674497  0.296717   
367         NaN    8415      NaN     NaN      40.98  0.412039  0.196769   
368         NaN    8422      NaN     NaN      16.84 -1.514793  0.158803   
369         NaN    8436      NaN     NaN      25.42 -0.853294  0.312367   
370         NaN    8454      NaN     NaN      23.84 -0.969149  0.457167   
371         NaN    8464      NaN     NaN      15.98 -0.611795  0.298180   
372         NaN    8926      NaN     NaN      36.15 -0.685223  0.147955   
373         NaN    8942      NaN     NaN      29.64  0.015998  0.110047   
374         NaN    9802      N

In [3]:
del esg_df['short_name']
del esg_df['zh_name']
del esg_df['sector']
del esg_df['stk_no']

In [4]:
esg_df=esg_df.dropna()

In [5]:
esg_df.corr().style.background_gradient(cmap="Blues")

In [6]:
from sklearn.linear_model import Lasso,LassoCV
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.linear_model import Ridge,RidgeCV

In [7]:
#設定訓練測試集 7:3
x_data = esg_df[['esg_score','年化夏普比率','年化波動度','平均Treynor ratio','平均現金股利率'
                 ,'平均本益比','總資產']]
y_data = esg_df[['全年平均收益率']]
train_x, test_x, train_y, test_y = train_test_split(x_data, y_data, test_size=0.3, random_state=42)

In [8]:
from sklearn import preprocessing
#建立StandardScaler物件
zscore = preprocessing.StandardScaler()
# 資料標準化
train_x = zscore.fit_transform(train_x)
test_x = zscore.fit_transform(test_x)
train_y = zscore.fit_transform(train_y)
test_y = zscore.fit_transform(test_y)

In [9]:
#Multivariable Regreesion

In [10]:
from sklearn import linear_model

In [11]:
regr=linear_model.LinearRegression()
regr.fit(train_x, train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
regr.intercept_   #截距

array([3.43419413e-17])

In [14]:
regr.coef_        #係數

array([[-0.01464901,  0.05068179, -0.08269387, -0.09793593,  0.07188542]])

In [15]:
regr.score(train_x,train_y)

0.017565208493006912

In [16]:
regr.score(test_x,test_y)

0.0019454133634381199

In [94]:
#lasso

In [17]:
clf_lasso=linear_model.Lasso(alpha=0.03636)
clf_lasso.fit(train_x, train_y)

Lasso(alpha=0.03636, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [18]:
#找最佳alpha值
clf_lasso = LassoCV(alphas=[1e-3, 1e-2, 1e-1, 1]).fit(train_x, train_y)
clf_lasso.score(train_x, train_y)

C:\Users\kay31\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:1100: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kay31\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.0

In [19]:
clf_lasso.coef_

array([-0.,  0., -0., -0.,  0.])

In [18]:
clf_lasso.intercept_

4.1693138222647903e-17

In [26]:
clf_lasso.score(train_x, train_y)

0.7325235725025949

In [19]:
clf_lasso.score(test_x, test_y)

0.7075772311340518

In [20]:
#ridge

In [21]:
clf_ridge=linear_model.Ridge(alpha=10)
clf_ridge.fit(train_x,train_y)

Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [22]:
#找最佳alpha值
clf_ridge = RidgeCV(alphas=[1e-3, 1e-2, 1e-1, 1]).fit(train_x, train_y)
clf_ridge.score(train_x, train_y)

0.7329815592869454

In [23]:
clf_ridge.coef_

array([[ 2.42815893e-02,  7.92523723e-01, -1.67820920e-01,
        -7.09245194e-05,  1.72885627e-02,  7.07029966e-03,
         6.74188514e-03]])

In [24]:
clf_ridge.intercept_

array([4.02393706e-17])

In [28]:
clf_ridge.score(train_x, train_y)

0.7329815592869454

In [25]:
clf_ridge.score(test_x, test_y)

0.704042245488459